## paths.R
## Source this file at the top of every script with: source(here::here("paths.R"))
##
## Defines all data paths relative to the repository root using the here package,
## so scripts run without modification on any machine provided the data files are
## placed in the locations described below and in data/external/README.md.
##
## DATA FOLDER SUMMARY
## data/bundled/   - small open datasets committed to the repository
## data/external/  - datasets the user must download separately (gitignored)
## data/processed/ - intermediate outputs; some generated by R scripts, some by QGIS

library(here)

# ── Root directories ──────────────────────────────────────────────────────────

PATH_BUNDLED   <- here("data", "bundled")
PATH_EXTERNAL  <- here("data", "external")
PATH_PROCESSED <- here("data", "processed")


# ╔══════════════════════════════════════════════════════════════════════════════
# ║  BUNDLED DATA  (committed to the repository)
# ╚══════════════════════════════════════════════════════════════════════════════

# WFD River Basin Districts shapefile
# Source: DATA.GOV.UK
# Used in: bio_data_prep.R, env_data_prep.R
PATH_WFD_BASINS <- file.path(PATH_BUNDLED, "WFD_River_Basin_Districts_Cycle_2.shp")

# WFD River Water Body Catchments shapefile
# Source: DATA.GOV.UK
# Used in: env_data_prep.R
PATH_WFD_CATCHMENTS <- file.path(PATH_BUNDLED, "WFD_River_Water_Body_Catchments_Cycle_2.shp")

# WFD water body classifications — HMWB and artificial water body flags
# Source: https://data.catchmentbasedapproach.org/maps/4cff14f14acc41d2ac7c2a6b1e200c10
# Used in: future_pred_data_prep.R
PATH_WFD_CLASS <- file.path(PATH_BUNDLED, "WFD_River_Canal_SWT_FullClass16_Eng_identity_6260226168399521051.csv")

# Schedule 2 (D4 indicator) freshwater species list
# Source: Extracted from https://www.legislation.gov.uk/uksi/2023/91/made
# Used in: bio_data_prep.R
PATH_SCHEDULE2 <- file.path(PATH_BUNDLED, "Schedule 2 freshwater species.csv")

# Waterbodies affected by abandoned mine drainage
# Source: DATA.GOV.UK
# Used in: env_data_prep.R
PATH_MINES <- file.path(PATH_BUNDLED, "DSTR08400_Waterbodies Impacted by Pollution from Abandoned Metal Mines_2019.xlsx")

# CAMS flow compliance bands
# Source: DATA.GOV.UK
# Used in: env_data_prep.R
PATH_FLOW_COMP <- file.path(PATH_BUNDLED, "Flow_Compliance_Bands.shp")

# Consented discharges to controlled waters in England
# Source: DATA.GOV.UK
# Used in: site_matching.R
PATH_CONSENTS <- file.path(PATH_BUNDLED, "_consents_all__202411051025.csv")

# England boundary for mapping
# Source: DATA.GOV.UK
# Used in: future_rainfall.R
PATH_COUNTRIES <- file.path(PATH_BUNDLED, "Countries_December_2017_Full_Clipped_Boundaries_in_Great_Britain.shp")


# ╔══════════════════════════════════════════════════════════════════════════════
# ║  EXTERNAL DATA  (user must download — see data/external/README.md)
# ╚══════════════════════════════════════════════════════════════════════════════

# ── EA Fish & Ecology Data Explorer ──────────────────────────────────────────
# Source: https://environment.data.gov.uk/ecology/explorer/
# Used in: bio_data_prep.R
PATH_EA_TAXON_INFO  <- file.path(PATH_EXTERNAL, "OPEN_DATA_TAXON_INFO.rds")
PATH_EA_INV_TAXA    <- file.path(PATH_EXTERNAL, "INV_OPEN_DATA_TAXA.rds")
PATH_EA_INV_SITE    <- file.path(PATH_EXTERNAL, "INV_OPEN_DATA_SITE.rds")
PATH_EA_INV_METRICS <- file.path(PATH_EXTERNAL, "INV_OPEN_DATA_METRICS.rds")
PATH_EA_FISH_COUNTS <- file.path(PATH_EXTERNAL, "FW_Fish_Counts.rds")

# ── EA Water Quality Archive ──────────────────────────────────────────────────
# Annual CSV files for 2002-2023, placed in data/external/wq_archive/
# Expected files: wq_archive/2002.csv, wq_archive/2003.csv, ..., wq_archive/2023.csv
# Source: https://environment.data.gov.uk/water-quality/view/landing
# Used in: wq_data_prep.R
PATH_WQ_ARCHIVE_DIR <- file.path(PATH_EXTERNAL, "wq_archive")

# ── OS Open Rivers ────────────────────────────────────────────────────────────
# NOT included in repository (223 MB). Download from Ordnance Survey and place
# all WatercourseLink shapefile components directly in data/external/.
# Source: https://www.ordnancesurvey.co.uk/products/os-open-rivers
# Used in: site_matching.R, env_data_prep.R
PATH_OS_RIVERS <- file.path(PATH_EXTERNAL, "WatercourseLink.shp")

# ── AMBER River Barriers Atlas ────────────────────────────────────────────────
# NOT included in repository. Download from AMBER Consortium and place in
# data/external/. Verify licence before use (expected: CC BY 4.0).
# Source: https://barriers.freshwatertools.eu/
# Used in: env_data_prep.R
PATH_BARRIERS <- file.path(PATH_EXTERNAL, "atlas-country-United-Kingdom.csv")

# ── ASR and CRI (Naura et al. 2016a, b) ──────────────────────────────────────
# NOT included in repository — not open data. Contact Marc Naura to request
# access to this dataset before running env_data_prep.R.
# Used in: env_data_prep.R
PATH_ASR_CRI <- file.path(PATH_EXTERNAL, "ASR_CRI.xlsx")

# ── HadUK-Grid monthly precipitation ─────────────────────────────────────────
# Monthly NetCDF files placed directly in data/external/.
# Source: https://catalogue.ceda.ac.uk/ (free CEDA account required)
# Used in: env_data_prep.R, historical_pred_data_prep.R, future_rainfall.R
#
# Annual files (one per year, 1989-2024):
#   rainfall_hadukgrid_uk_5km_mon_<YYYY>01-<YYYY>12.nc
# 30-year monthly mean files:
#   rainfall_hadukgrid_uk_5km_mon-30y_196101-199012.nc
#   rainfall_hadukgrid_uk_5km_mon-30y_199101-202012.nc
PATH_HADUK_DIR <- PATH_EXTERNAL

# Convenience function: returns path for a given year's annual HadUK file
haduk_annual_path <- function(year) {
  file.path(PATH_HADUK_DIR,
    paste0("rainfall_hadukgrid_uk_5km_mon_", year, "01-", year, "12.nc"))
}

# Paths for the two 30-year monthly mean files
PATH_HADUK_30Y_1961_1990 <- file.path(PATH_HADUK_DIR,
  "rainfall_hadukgrid_uk_5km_mon-30y_196101-199012.nc")
PATH_HADUK_30Y_1991_2020 <- file.path(PATH_HADUK_DIR,
  "rainfall_hadukgrid_uk_5km_mon-30y_199101-202012.nc")

# ── CHESS-SCAPE projected precipitation ──────────────────────────────────────
# NOT included in repository (~3.3 GB total). Download from CEDA and place the
# three NetCDF files directly in data/external/.
# Source: https://catalogue.ceda.ac.uk/uuid/8194b416cbee482b89e0dfbe17c5786c/
# Used in: future_rainfall.R
#
# Expected filenames:
#   chess-scape_rcp26_bias-corrected_01_pr_uk_1km_monthly_19801201-20801130.nc
#   chess-scape_rcp60_bias-corrected_01_pr_uk_1km_monthly_19801201-20801130.nc
#   chess-scape_rcp85_bias-corrected_01_pr_uk_1km_monthly_19801201-20801130.nc
PATH_CHESS_DIR <- PATH_EXTERNAL

# Convenience function: returns full path for a given RCP (26, 60, or 85)
chess_scape_path <- function(rcp) {
  file.path(PATH_CHESS_DIR,
    paste0("chess-scape_rcp", rcp,
           "_bias-corrected_01_pr_uk_1km_monthly_19801201-20801130.nc"))
}

# ── UK CEH Land Cover Map 2020 ────────────────────────────────────────────────
# NOT included in repository. Download the 1 km target class percentage rasters
# from UKCEH and place in data/external/.
# Source: https://catalogue.ceh.ac.uk/documents/304e5acd-bea3-46f2-abc0-20bcc174e15b
# Used in: inla_spatial_pred.R
PATH_LCM <- file.path(PATH_EXTERNAL, "gb2020lcm1km_percentage_target.tif")


# ╔══════════════════════════════════════════════════════════════════════════════
# ║  PROCESSED DATA  (intermediate outputs — not all committed to repository)
# ╚══════════════════════════════════════════════════════════════════════════════

# Snapped biological monitoring sites
# Generated by: QGIS snapping procedure (see site_matching.R header for details)
# Committed to repository in data/processed/
# Used in: site_matching.R
PATH_META_SNAP <- file.path(PATH_PROCESSED, "meta_snap.shp")

# Snapped EA water quality monitoring sites
# Generated by: QGIS snapping procedure (see site_matching.R header for details)
# Committed to repository in data/processed/
# Used in: site_matching.R
PATH_WQ_SNAP <- file.path(PATH_PROCESSED, "ea_wq_snap.shp")

# Snapped consented discharge locations (STWs and CSOs)
# Generated by: QGIS snapping procedure (see site_matching.R header for details)
# Committed to repository in data/processed/
# Used in: site_matching.R, env_data_prep.R
PATH_STWS_SNAP <- file.path(PATH_PROCESSED, "stws_snap.shp")

# RICT PCA axes raster (PC1 and PC2 only, 55 MB)
# Committed to repository in data/processed/
# Used in: env_data_prep.R
PATH_RICT <- file.path(PATH_PROCESSED, "rict_pca_axes.tif")

